### ISSUE TITLE
When linking a picture of the real wagon it appear in the box for the model

### ISSUE THREAD

**Issue by etxbct** [tellurianinteractive/Tellurian.Trains.WagonCardApp#16]
For wagons and cargo cars the picture of the real car appears in the box for the model. If a card is created for a locomotive the picture appears in correct boxes.

![image](https://user-images.githubusercontent.com/22001932/194539385-0ae573b1-1dc6-4a4c-bde2-d4e85a0328c5.png)

**Comment by fjallemark** [comment]
Fixed in 2.1.17.
