### ISSUE TITLE
File size when uploading back a saved file is above limit of 700k

### ISSUE THREAD

**Issue by thomasnilsen** [tellurianinteractive/Tellurian.Trains.WagonCardApp#18]
Should be possible to upload all downloaded files. Either by not allowing to save a "to big file" or have some way of warning to save without images. That way upload would be possible. Quick fix would be to increase the limit of upload to 1MB?

**Comment by fjallemark** [comment]
Thanks Thomas for noting this. File size is now increased to 4MB. Let me know if this is not enough.

**Comment by thomasnilsen** [comment]
Thanks! Solved my problem.

**Comment by fjallemark** [comment]
Good!
