### ISSUE TITLE
Inventory Card actual print does not looks like preview

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.WagonCardApp#19]
The printed inventory card does not look like the preview. 
On the actual print out the inventory, card overlaps the wagon card. 

![image](https://user-images.githubusercontent.com/57874863/210189999-2a22c79e-9600-4a8a-add9-69d32bad9ab7.png)

![image](https://user-images.githubusercontent.com/57874863/210190030-9a8f7c2e-f62d-4425-9607-299029bf954c.png)

Running Chrome Version 108.0.5359.125 (Officiell version) (64 bitar)

**Comment by AlexEhn** [comment]
I works when MS Edge is used as browser.

![image](https://user-images.githubusercontent.com/57874863/210252624-ebc7ad09-d984-4203-9d13-fe8182d86820.jpeg)

**Comment by fjallemark** [comment]
This is now fixed.
