### ISSUE TITLE
Only one type of marking possible as Owners marking

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.WagonCardApp#21]
The owner marking only allow for one of the four types to be seen. Yellow, blue, green, or orange in the picture. 
![image](https://user-images.githubusercontent.com/57874863/211282423-9e9a37e9-7fd9-4dc9-9bf5-5b563f86ef66.png)

I want to have my owner's colors AND the Inventory number on the card and wagon.  But that is not possible at the moment. 

One can also argue that the parameter "inventory number" is not necessarily an owner's marking. It might be used as it is, but the inventory number is mainly used for the owner to keep track of the wagon and card, not for others to recognize who's wagon it is that is found somewhere on the layout.

**Comment by fjallemark** [comment]
Inventory number can now be given in combination with any type of owners marking.

**Comment by SwedX87** [comment]
Sry if i open this again ;)
in denmark we use 3 or 4 colour codes 
is it possible to add an exstra 

Best Regards 
Henrik Philippsen
