### ISSUE TITLE
Motorleistung

### ISSUE THREAD

**Issue by pischky** [tellurianinteractive/Tellurian.Trains.WagonCardApp#22]
I do not know what is used in other languages but I assume that "Motorleistung" in german is a translation error. I assume
that should be "Dauerleistung" (or less probally Stundenleistung). For usage in german see wikipedia:
https://de.wikipedia.org/wiki/Bombardier_Traxx

Anyway: thanks for that nice application!!!

**Comment by fjallemark** [comment]
Hi Martin, this will be fixed in the next release 2.1.23. Thanks for your contribution.
