### ISSUE TITLE
Chrome reshapes inventory card when printing

### ISSUE THREAD

**Issue by TheLindblomer** [tellurianinteractive/Tellurian.Trains.WagonCardApp#23]
Inventory card's broken when reaching the printing dialogue. The image below speaks for itself.

Visa utskrift -> Ctrl+P

This problem only seems to occur when using Google Chrome's browser to print (v113.0.5672.127).

![bild](https://github.com/tellurianinteractive/Tellurian.Trains.WagonCardApp/assets/61082616/3603be7d-8cb7-4f78-a13b-c0db6dae8e37)

**Comment by fjallemark** [comment]
This is probably a result of your browser caching an old version of the CSS-file that controls the layout of the print. Do a **hard reload** in your browser to reload all content. I have tested in Chrome and it prints just fine.
