### ISSUE TITLE
Markings no longer available (loco-card)

### ISSUE THREAD

**Issue by TheLindblomer** [tellurianinteractive/Tellurian.Trains.WagonCardApp#24]
Can no longer specify markings on the locomotive card. This includes signatures, colours, images, etc.
I've tried using Google Chrome, Firefox and Microsoft Edge to no avail. Even tried deleting all website data.

This issue appeared today (16/5) and had no trouble with it before noon.

Passenger and freight cards doesn't seem to be affected by this.

**Comment by fjallemark** [comment]
Bug fix in release 2.1.23. Sorry for the delay in fixning this issue. Do a *hard reload* (typically holding SHIFT down while refreshing page) to get all most recent files downloaded.
