### ISSUE TITLE
Loco function label for UT4

### ISSUE THREAD

**Issue by fjallemark** [tellurianinteractive/Tellurian.Trains.WagonCardApp#25]
I can see there is a template for function buttons for a FREMO-FRED throttle. Do you think it is possible to have a choice between it and then UT4, more and more also use UT4 handles?
Henrik Philippsen

**Comment by SwedX87** [comment]
Thank you very much ofr creating this topic for me,
iam the original guy who proposed this feature 

it could be nice also to choose UT4 or UT6 besides the normal FRED Controller ;)
UT4 has F0-F6 and shift+F7-F12
UT6 has F0-F28

**Comment by SwedX87** [comment]
Hi Fjallemark
PLZ Delete this Tread i will create an better one more detailed

**Comment by fjallemark** [comment]
Yes, I will do in a while. Please, open a new issue with details like measurements.
