### ISSUE TITLE
DCC calculator CV29 mismatch

### ISSUE THREAD

**Issue by Andersson-i-Rakvattnet** [tellurianinteractive/Tellurian.Trains.WagonCardApp#29]
Hi

When having an address based on CV1 you suggest a value of 4 for CV 29 (analog mode enable). This is not recommended by FREMO etc
When having an address based on CV17-18 you suggest a value of 34 (2+32, 128 speedsteps + long adress)

I suggest that you correct the proposed value for CV 29 for short addresses to 2. 

Thanks for a great app!
Jerker

**Comment by fjallemark** [comment]
Fixed in release 2.2.0. Thanks for your support!
